### ISSUE TITLE
key patch error

### ISSUE THREAD

**Issue by AllSystemsGo** [Fevix/Avali#116]
[18:42:02.258] Error: Could not apply patch from backend: Folder <../giraffe_storage/mods/Avali-2.3.0/.>.  Cau
sed by: (JsonPatchException) Could not apply patch to base. (JsonPatchException) Could not apply operation to
base. (TraversalException) No such key 'items' in pathApply("/items/avali")

...the mod still seems to work but I found this when going through the startup sequence's logs.

**Comment by Fevix** [comment]
That looks like the patch files for .npcs
@Devani1 @thakyZ any clue what the issue here is?

**Comment by Fevix** [comment]
Checked myself. There is no race-specific items path in the vanilla Starbound's .npctype files. We may have to define our own avalichefmerchant.npctype and such with the desired cosmetics.

**Comment by AllSystemsGo** [comment]
Hello,

I have a few more errors to report. Would you prefer 1 issue per error, or would you like them lumped into a single issue?

Thanks

**Comment by Fevix** [comment]
1 issue per error

**Comment by Jeadbe** [comment]
After a morning of banging my head on the keyboard, I have learned 2 things:

1) it is specifically the 'friendlyguard.npctype.patch' file,

2) it seems to be related to Avali guards spawning with the default armor entry. as in, they will use the default armor from 'friendlyguard_accelerator.npctype' instead of the entries added by 'friendlyguard_accelerator.npctype.patch'



haven't found a fix yet, tho

**Comment by Fevix** [comment]
Fixed in #118
