### ISSUE TITLE
(Fixed)Firelance railgun particle not accurate

### ISSUE THREAD

**Issue by origamania** [Fevix/Avali#259]
When firing the Firelance, the long particle does not follow the actual projectile. It goes at a slightly higher angle than the angle at which the Firelance is shot, but the actual damaging projectile follows the expected trajectory. Tested with FM1, FM2, and a tier 3 AM1 Firelance.

**Comment by origamania** [comment]
Also, I wonder if it would be possible to reduce the light level of the projectiles, especially for the miniguns. 
It makes flashlights redundant since the bullets emit so much light.

**Comment by Fevix** [comment]
Bullets require energy, so flashlights remain relevant. if you REALLY want to make flashlights irrelevant, get a Light III augment for all of your EPPs

As for the firelance, this issue is known, as it's currently a muzzleflash (Which is attached to the weapon)
I'm honestly considering making the projectile yellow instead of invisible like it is.

**Comment by Fevix** [comment]
Railgun has been fixed in dev version (Muzzleflash removed, projectile made visible)

**Comment by Fevix** [comment]
Leaving this open to prevent further similar issues from being reported
