### ISSUE TITLE
No such item 'flagavali'

### ISSUE THREAD

**Issue by jotemair** [Fevix/Avali#284]
I just started a new Avali character. I'm really liking the mod so far, but now I'm getting an error. Yesterday the game worked fine, but today, when I select my character to start the game, the game quits to desktop. I haven't used GitHub before, but I'll figure out how to attach the log file.

**Comment by jotemair** [comment]
Found it. GitHub freaks out from .log files, so I renamed it.
[starbound.log.txt](https://github.com/Fevix/Avali/files/414734/starbound.log.txt)

**Comment by gamrguy** [comment]
There was a conflict with the Unbreakable Teleporters mod which arose when he made an accident with Avali support (it makes flags require more than 1 hit of a MM to prevent a ghost teleport point bug). This issue has since been fixed by the author and everything works properly now.

Consider this issue closed.
